# Generated by Django 4.2.2 on 2025-02-08 15:34

from django.db import migrations, models
import django.db.models.deletion
import gestion_deportiva.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('Terrestrial', 'Terrestrial'), ('Aquatic', 'Aquatic')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('hour_begin', models.TimeField()),
                ('hour_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numberOf_facilities', models.IntegerField()),
                ('description', models.TextField()),
                ('hour_price', models.FloatField()),
                ('facility_type', models.CharField(choices=[('Outside', 'Outside'), ('Inside', 'Inside')], max_length=10)),
                ('schedules', models.ManyToManyField(blank=True, related_name='sport_facilities', to='gestion_deportiva.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gestion_deportiva.models.photo_upload_path)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gestion_deportiva.activity')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gestion_deportiva.sportfacility')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bonus_type', models.CharField(choices=[('annual', 'Bono Anual'), ('semester', 'Bono Semestral'), ('single', 'Bono Sesión Única')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='gestion_deportiva.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='activities', to='gestion_deportiva.schedule'),
        ),
    ]
