# Generated by Django 5.1.5 on 2025-02-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_deportiva', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='default_profile.png', upload_to='users/'),
        ),
    ]
