# Generated by Django 5.1.5 on 2025-02-26 10:17

import gestion_deportiva.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_deportiva', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='default_profile.png', upload_to=gestion_deportiva.models.User.user_directory_path),
        ),
    ]
