# Generated by Django 5.1.6 on 2025-03-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_deportiva', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('notUAM', 'Usuario no perteneciente a la UAM'), ('student', 'Estudiante UAM'), ('professor', 'Personal docente o investigador UAM'), ('administrative', 'Personal Administrativo UAM'), ('alumni', 'Ex-alumno de la UAM')], max_length=30, null=True),
        ),
    ]
